SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `v7ocf_organizer_blocks`;
DROP TABLE IF EXISTS `v7ocf_organizer_buildings`;
DROP TABLE IF EXISTS `v7ocf_organizer_campuses`;
DROP TABLE IF EXISTS `v7ocf_organizer_categories`;
DROP TABLE IF EXISTS `v7ocf_organizer_course_participants`;
DROP TABLE IF EXISTS `v7ocf_organizer_courses`;
DROP TABLE IF EXISTS `v7ocf_organizer_curricula`;
DROP TABLE IF EXISTS `v7ocf_organizer_event_coordinators`;
DROP TABLE IF EXISTS `v7ocf_organizer_events`;
DROP TABLE IF EXISTS `v7ocf_organizer_group_publishing`;
DROP TABLE IF EXISTS `v7ocf_organizer_groups`;
DROP TABLE IF EXISTS `v7ocf_organizer_holidays`;
DROP TABLE IF EXISTS `v7ocf_organizer_instance_groups`;
DROP TABLE IF EXISTS `v7ocf_organizer_instance_participants`;
DROP TABLE IF EXISTS `v7ocf_organizer_instance_persons`;
DROP TABLE IF EXISTS `v7ocf_organizer_instance_rooms`;
DROP TABLE IF EXISTS `v7ocf_organizer_instances`;
DROP TABLE IF EXISTS `v7ocf_organizer_methods`;
DROP TABLE IF EXISTS `v7ocf_organizer_monitors`;
DROP TABLE IF EXISTS `v7ocf_organizer_participants`;
DROP TABLE IF EXISTS `v7ocf_organizer_pools`;
DROP TABLE IF EXISTS `v7ocf_organizer_prerequisites`;
DROP TABLE IF EXISTS `v7ocf_organizer_programs`;
DROP TABLE IF EXISTS `v7ocf_organizer_roles`;
DROP TABLE IF EXISTS `v7ocf_organizer_rooms`;
DROP TABLE IF EXISTS `v7ocf_organizer_roomtypes`;
DROP TABLE IF EXISTS `v7ocf_organizer_runs`;
DROP TABLE IF EXISTS `v7ocf_organizer_schedules`;
DROP TABLE IF EXISTS `v7ocf_organizer_subject_events`;
DROP TABLE IF EXISTS `v7ocf_organizer_subject_persons`;
DROP TABLE IF EXISTS `v7ocf_organizer_subjects`;
DROP TABLE IF EXISTS `v7ocf_organizer_terms`;
DROP TABLE IF EXISTS `v7ocf_organizer_units`;

SET foreign_key_checks = 1;