SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `#__organizer_associations`;
DROP TABLE IF EXISTS `#__organizer_blocks`;
DROP TABLE IF EXISTS `#__organizer_bookings`;
DROP TABLE IF EXISTS `#__organizer_buildings`;
DROP TABLE IF EXISTS `#__organizer_campuses`;
DROP TABLE IF EXISTS `#__organizer_categories`;
DROP TABLE IF EXISTS `#__organizer_cleaning_groups`;
DROP TABLE IF EXISTS `#__organizer_colors`;
DROP TABLE IF EXISTS `#__organizer_course_participants`;
DROP TABLE IF EXISTS `#__organizer_courses`;
DROP TABLE IF EXISTS `#__organizer_curricula`;
DROP TABLE IF EXISTS `#__organizer_degrees`;
DROP TABLE IF EXISTS `#__organizer_equipment`;
DROP TABLE IF EXISTS `#__organizer_event_coordinators`;
DROP TABLE IF EXISTS `#__organizer_events`;
DROP TABLE IF EXISTS `#__organizer_field_colors`;
DROP TABLE IF EXISTS `#__organizer_fields`;
DROP TABLE IF EXISTS `#__organizer_frequencies`;
DROP TABLE IF EXISTS `#__organizer_grids`;
DROP TABLE IF EXISTS `#__organizer_group_publishing`;
DROP TABLE IF EXISTS `#__organizer_groups`;
DROP TABLE IF EXISTS `#__organizer_holidays`;
DROP TABLE IF EXISTS `#__organizer_instance_groups`;
DROP TABLE IF EXISTS `#__organizer_instance_participants`;
DROP TABLE IF EXISTS `#__organizer_instance_persons`;
DROP TABLE IF EXISTS `#__organizer_instance_rooms`;
DROP TABLE IF EXISTS `#__organizer_instances`;
DROP TABLE IF EXISTS `#__organizer_methods`;
DROP TABLE IF EXISTS `#__organizer_monitors`;
DROP TABLE IF EXISTS `#__organizer_organizations`;
DROP TABLE IF EXISTS `#__organizer_participants`;
DROP TABLE IF EXISTS `#__organizer_persons`;
DROP TABLE IF EXISTS `#__organizer_pools`;
DROP TABLE IF EXISTS `#__organizer_prerequisites`;
DROP TABLE IF EXISTS `#__organizer_programs`;
DROP TABLE IF EXISTS `#__organizer_roles`;
DROP TABLE IF EXISTS `#__organizer_room_equipment`;
DROP TABLE IF EXISTS `#__organizer_roomkeys`;
DROP TABLE IF EXISTS `#__organizer_rooms`;
DROP TABLE IF EXISTS `#__organizer_roomtypes`;
DROP TABLE IF EXISTS `#__organizer_runs`;
DROP TABLE IF EXISTS `#__organizer_schedules`;
DROP TABLE IF EXISTS `#__organizer_subject_events`;
DROP TABLE IF EXISTS `#__organizer_subject_persons`;
DROP TABLE IF EXISTS `#__organizer_subjects`;
DROP TABLE IF EXISTS `#__organizer_terms`;
DROP TABLE IF EXISTS `#__organizer_units`;
DROP TABLE IF EXISTS `#__organizer_use_groups`;

SET foreign_key_checks = 1;