<?php
/**
 * @package     Organizer
 * @extension   pkg_organizer
 * @author      James Antrim, <james.antrim@nm.thm.de>
 * @copyright   2023 TH Mittelhessen
 * @license     GNU GPL v.3
 * @link        www.thm.de
 */

namespace THM\Organizer\Controllers;

use THM\Organizer\Adapters\Application;
use THM\Organizer\Helpers\Can;

/**
 * @inheritDoc
 */
class Person extends FormController
{
    protected string $list = 'Persons';

    /**
     * @inheritDoc
     */
    protected function authorize(): void
    {
        if (!Can::manage('persons')) {
            Application::error(403);
        }
    }

    /**
     * @inheritDoc
     */
    protected function prepareData(): array
    {
        return parent::prepareData(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function validate(array &$data, array $required = []): void
    {
        parent::validate($data, $required); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritDoc
     */
    /*public function save(array $data = [])
    {
        $this->selected = Input::getSelectedIDs();
        $this->authorize();

        $data  = empty($data) ? Input::getFormItems()->toArray() : $data;
        $table = new Tables\Persons();

        if (!$table->save($data)) {
            return false;
        }

        $data['id'] = $table->id;

        if (!empty($data['organizationIDs']) and !$this->updateAssociations($data['id'], $data['organizationIDs'])) {
            return false;
        }

        return $table->id;
    }*/
}