name: Test component installation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Testausgaben
      run: pwd
      run: ls -lA
      run: tree
