name: Test component installation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: "sudo apt-get install tree"
      - name: Stop mysqld
        run: "sudo systemctl stop mysqld"
      - name: "Install mariadb"
        uses: getong/mariadb-action@v1.1
        with:
          mysql database: "joomla"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testausgaben
        run: "pwd && ls -lA && tree"
